### PR TITLE
Milestone:1 Embedding images and video (Youtube video page)

### PR DESCRIPTION
**Pull request by talhawaqar**
In this milestone we

-  Learn basic HTML and CSS

- Learn how to embed video and images

- Learn the use of CSS grid and flexbox

### CODE REVIEW

**Comment by trekab** [comment]
# Changes Required!
Hi @talhawaqar and @visva-dev. Great job so far! :clap: :clap: :clap:
However, we have some minor changes attend to;
* The navigation bar elements appear misaligned. The embedded images on the right should be on the rightmost end of the navigation and the search bar should be in the middle.
* The main video section icons(subscribe, share, and more buttons) should be positioned similarly to the page being cloned.

__Kindly work on the above changes and submit another code review request__
_Feel free to reach me on slack if necessary_
__Treasure Kabareebe__

**Comment by santiago-dev96** [comment]
## Pull Request under Review by @santiago-rodrig (TSE)

**Review by santiago-dev96 — CHANGES_REQUESTED** [review]
## We have issues to resolve

Good job! But there are a few details that do need to be treated.

1. Your pull request summary must be descriptive as specified [here](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/66243642/)
2. According to the project requirements, you need to place **three images** on the right side of the navigation bar
image
3. Your **number of views** element is misplaced (image below)
image
image

---

Please submit another CRR (Code Review Request) after implementing the changes. Have a nice day.

**Review by rammazzoti2000 — APPROVED** [review]
### Hello @talhawaqar    and @visva-dev , I'm Alex, your reviewer for this PR :man_astronaut: 
## Project Approved :tada: :rocket: 
Congrats in completing all the changes required by previous TSE :star2: 
You also used proper html syntax and good css practices, congrats on that.
### :green_circle:  This is only optional and is not required in any way, but it would be great to have :green_circle: 
- [ ] [OPTIONAL] Instead of getting images with a background color or taking screenshots of icons use actual icons(). <em>You can find them in sites like [fontaweome](https://github.com/rida-elbahtouri/rida-aye-youtube/pull/fontawesome.com/), they are easier to style, you style icons like text, and they have a transparent background.
In case you don't want to use icons you can also search for png images with transparent background on google images or svg images.</em>

[Read this article if you are not sure which type of image you should use for each case in web development.](https://www.pagecloud.com/blog/web-images-png-vs-jpg-vs-gif-vs-svg)

  [Read this article if you want to know more about SVG images, they are great for logos!](https://css-tricks.com/using-svg/)
#
#### Please merge and keep going! See you at the top :medal_military: 
Cheers and Happy coding! :clap: 
Code review by Alexandru Bangau

(Feel free to contact me on slack by the handle of alexandru if you have any additional question)</em>

**Review by rammazzoti2000 — APPROVED** [review]
#### Status: Approved

**Pull request merged**
